name       : eqonomize
version    : 1.4.2
release    : 8
source     :
    - https://github.com/Eqonomize/Eqonomize/archive/v1.4.2.tar.gz : 4d0789e3532dfda46d6792fd40bb947eceb4af082b0ecb4d224aa28e3425eb2b
license    : GPL-3.0-or-later
component  : office.finance
summary    : Eqonomize! is a cross-platform personal accounting software, with focus on efficiency and ease of use for the small household economy.
description: |
    Eqonomize! provides a complete solution, with bookkeeping by double entry and support for scheduled recurring transactions, security investments, and budgeting. It gives a clear overview of past and present transactions, and development of incomes and expenses, with descriptive tables and charts, as well as an approximation of future account values.
builddeps  :
    - pkgconfig(Qt5Charts)
setup      : |
    %qmake CONFIG+=release PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
