name       : eqonomize
version    : 1.1
release    : 1
source     :
    - https://github.com/Eqonomize/eqonomize/releases/download/v1.1.0a/eqonomize-1.1.tar.gz : 69c466deec7f518bd17ff52f78ca1cbf55373f2df6a2657f555926ae711df772
license    : GPL-3.0
component  : office.finance
summary    : Eqonomize! is a cross-platform personal accounting software, with focus on efficiency and ease of use for the small household economy.
description: |
    Eqonomize! provides a complete solution, with bookkeeping by double entry and support for scheduled recurring transactions, security investments, and budgeting. It gives a clear overview of past and present transactions, and development of incomes and expenses, with descriptive tables and charts, as well as an approximation of future account values. 
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Charts)
    - pkgconfig(gl)
setup      : |
    %qmake CONFIG+=release PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
