name       : eqonomize
version    : '1.2'
release    : 2
source     :
    - https://github.com/Eqonomize/eqonomize/releases/download/v1.2.0/eqonomize-1.2.tar.gz : d098da169cea060b5d1605cc9d7a37582eff83e2f3779546565d4feac0afc0c6
license    : GPL-3.0
component  : office.finance
summary    : Eqonomize! is a cross-platform personal accounting software, with focus on efficiency and ease of use for the small household economy.
description: |
    Eqonomize! provides a complete solution, with bookkeeping by double entry and support for scheduled recurring transactions, security investments, and budgeting. It gives a clear overview of past and present transactions, and development of incomes and expenses, with descriptive tables and charts, as well as an approximation of future account values. 
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Charts)
    - pkgconfig(gl)
setup      : |
    %qmake CONFIG+=release PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
