name       : eqonomize
version    : 1.5.0
release    : 10
source     :
    - https://github.com/Eqonomize/Eqonomize/releases/download/v1.5.0/eqonomize-1.5.0.tar.gz : 6ca5383d49f65aa521faf4103b7d2910bad9dd277319a1ce4d92669d2d490672
homepage   : https://eqonomize.github.io/
license    : GPL-3.0-or-later
component  : office.finance
summary    : Eqonomize! is a cross-platform personal accounting software, with focus on efficiency and ease of use for the small household economy.
description: |
    Eqonomize! provides a complete solution, with bookkeeping by double entry and support for scheduled recurring transactions, security investments, and budgeting. It gives a clear overview of past and present transactions, and development of incomes and expenses, with descriptive tables and charts, as well as an approximation of future account values.
builddeps  :
    - pkgconfig(Qt5Charts)
setup      : |
    %qmake CONFIG+=release PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
