name       : eqonomize
version    : 1.5.5
release    : 17
source     :
    - https://github.com/Eqonomize/Eqonomize/releases/download/v1.5.5/eqonomize-1.5.5.tar.gz : d5fcb65659c8184d9d97588b044468960ed1355b99b6686eea8f3fb87f693685
homepage   : https://eqonomize.github.io/
license    : GPL-3.0-or-later
component  : office.finance
summary    : Eqonomize! is an efficient and easy accounting for personal financies
description: |
    Eqonomize! is a cross-platform personal accounting software, with focus on efficiency and ease of use for small households. Eqonomize! provides a complete solution, with bookkeeping by double entry and support for scheduled recurring transactions, security investments, and budgeting. It gives a clear overview of past and present transactions, and development of incomes and expenses, with descriptive tables and charts, as well as an approximation of future account values.
builddeps  :
    - pkgconfig(Qt5Charts)
setup      : |
    %qmake CONFIG+=release PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
